openapi: 3.2.0
info:
  title: AElf Task Queue Status API
  version: v1
tags:
- name: TaskQueueStatus
paths:
  /api/blockChain/taskQueueStatus:
    get:
      tags:
      - TaskQueueStatus
      responses:
        '200':
          description: Success
          content:
            text/plain; v=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AElf.WebApp.Application.Chain.Dto.TaskQueueInfoDto'
            application/json; v=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AElf.WebApp.Application.Chain.Dto.TaskQueueInfoDto'
            text/json; v=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AElf.WebApp.Application.Chain.Dto.TaskQueueInfoDto'
            application/x-protobuf; v=1.0:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AElf.WebApp.Application.Chain.Dto.TaskQueueInfoDto'
        '403':
          description: Forbidden
          content:
            text/plain; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            text/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/x-protobuf; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
        '401':
          description: Unauthorized
          content:
            text/plain; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            text/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/x-protobuf; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
        '400':
          description: Bad Request
          content:
            text/plain; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            text/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/x-protobuf; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
        '404':
          description: Not Found
          content:
            text/plain; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            text/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/x-protobuf; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
        '501':
          description: Server Error
          content:
            text/plain; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            text/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/x-protobuf; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
        '500':
          description: Server Error
          content:
            text/plain; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            text/json; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
            application/x-protobuf; v=1.0:
              schema:
                $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorResponse'
      summary: Get api block chain task queue status
      x-summary-source: derived
      operationId: getApiBlockChainTaskQueueStatus
      x-operation-id-source: derived
components:
  schemas:
    AElf.WebApp.Application.Chain.Dto.TaskQueueInfoDto:
      type: object
      properties:
        Name:
          type:
          - string
          - 'null'
        Size:
          type: integer
          format: int32
      additionalProperties: false
    Volo.Abp.Http.RemoteServiceErrorResponse:
      type: object
      properties:
        Error:
          $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceErrorInfo'
      additionalProperties: false
    Volo.Abp.Http.RemoteServiceValidationErrorInfo:
      type: object
      properties:
        Message:
          type:
          - string
          - 'null'
        Members:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    Volo.Abp.Http.RemoteServiceErrorInfo:
      type: object
      properties:
        Code:
          type:
          - string
          - 'null'
        Message:
          type:
          - string
          - 'null'
        Details:
          type:
          - string
          - 'null'
        Data:
          type:
          - object
          - 'null'
          additionalProperties: {}
        ValidationErrors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Volo.Abp.Http.RemoteServiceValidationErrorInfo'
      additionalProperties: false
